name: deploy

on:
  workflow-call:
    inputs:
      python-version:
        type: string
        default: "3.8"
        description: "Python version used to test and build the package"
    secrets:
      PYPI_TOKEN:
        required: true
        description: "Token used to deploy package on PyPI"

jobs:
  publish:
    name: 📦 PyPI (🐍 ${{ input.python-version }})

    steps:
      - uses: actions/checkout@master
      - name: Setup Python 🐍
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ input.python-version }}
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-path: ~/.virtualenvs
          installer-parallel: true
      - name: Cache Poetry virtualenv
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.virtualenvs
          key: ${{ runner.os }}-py-${{ steps.setup-python.outputs.python-version }}-poetry-${{ hashFiles('poetry.lock') }}
      - name: Install package
        run: |
          poetry install
          # run tests just before deployment
          pip install poethepoet
          poe test
      - name: Package the distribution
        run: |
          # add version management tool, same poetry env
          PIP="$(head -n1 $(which poetry) | cut -c 3-) -m pip"
          ${PIP} install poetry-dynamic-versioning
          # package the pure python wheel
          poetry build
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_TOKEN }}
