name: deploy

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        required: false
        description: >
          Python version used to test and build the package (for logging
          purpose only)
    secrets:
      PYPI_TOKEN:
        required: true
        description: "Token used to deploy package on PyPI"

jobs:
  publish:
    name: 📦 PyPI (🐍 ${{ inputs.python-version }})
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          # run tests just before deployment
          poe test
      - name: Package the distribution
        run: |
          # package the pure python wheel
          poetry build
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_TOKEN }}
